version: "3.0"

services:
  api:
    container_name: "voice_recognizer_api"
    volumes:
      - ./app:/app
    build: ./
    shm_size: '32gb'
    ports:
      - 8089:8080

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
            - count: 1
            - capabilities: [gpu]